# Generated by Django 4.1.1 on 2022-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_value',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
