# Generated by Django 4.1.1 on 2022-10-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_country_user_created_from_dashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_expired',
        ),
    ]
