# Generated by Django 4.1.1 on 2023-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_test_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_cover",
        ),
    ]
