# Generated by Django 4.1.1 on 2023-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_profile_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
