# Generated by Django 4.1.1 on 2022-10-10 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_otp_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 22, 10, 55, 883462)),
        ),
    ]
