# Generated by Django 4.1.1 on 2023-06-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
