# Generated by Django 4.1.1 on 2022-10-16 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_fname_user_fullname_remove_user_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 21, 24, 51, 607854)),
        ),
    ]
