# Generated by Django 4.1.1 on 2022-10-18 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otp_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 12, 14, 30, 529794)),
        ),
    ]
