# Generated by Django 4.1.1 on 2022-12-04 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_user_city_remove_user_country_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 14, 8, 18, 901223)),
        ),
    ]
