# Generated by Django 4.1.1 on 2022-12-04 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_otp_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 14, 38, 21, 680281)),
        ),
    ]
