# Generated by Django 4.1.1 on 2022-12-04 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_otp_expiry_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 15, 0, 24, 483031)),
        ),
    ]
