# Generated by Django 4.1.1 on 2023-05-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_recentlywatched"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("thumbnail_url", models.URLField()),
                ("published_at", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
    ]
