# Generated by Django 4.1.1 on 2022-10-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_leader_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacher',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
