# Generated by Django 4.1.1 on 2022-10-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_preacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='picture',
            field=models.ImageField(blank=True, upload_to='assets/leader_pics/'),
        ),
        migrations.AlterField(
            model_name='preacher',
            name='picture',
            field=models.ImageField(blank=True, upload_to='assets/preacher_pics/'),
        ),
    ]
