# Generated by Django 4.1.1 on 2023-05-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_youtubevideo_catetory"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="preacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube_videos",
                to="dashboard.preacher",
            ),
        ),
    ]
