# Generated by Django 4.1.1 on 2022-10-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_messagecategory_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='description',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='assets/messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video')], default='video', max_length=10),
        ),
    ]
