# Generated by Django 4.1.1 on 2023-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_youtubevideo_preacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="assets/gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
