# Generated by Django 4.1.1 on 2023-06-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_gallery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtubevideo",
            old_name="catetory",
            new_name="category",
        ),
    ]
