# Generated by Django 4.1.1 on 2022-10-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctrine',
            name='created_by',
        ),
    ]
