# Generated by Django 4.1.1 on 2023-06-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_catetory_youtubevideo_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="message",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.youtubevideo",
            ),
        ),
    ]
