# Generated by Django 4.1.1 on 2022-10-22 23:03

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_doctrine_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('transaction_id', models.CharField(default=dashboard.models.Donation.generate_transaction_id, max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
