# Generated by Django 4.1.1 on 2022-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='assets/category_thumbnails/'),
        ),
    ]
