# Generated by Django 4.1.1 on 2023-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_gallerycategory_gallery_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("document", models.FileField(upload_to="assets/documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
