# Generated by Django 4.1.1 on 2022-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_messagecategory_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='category_thumbnails/'),
        ),
    ]
