# Generated by Django 4.1.1 on 2023-06-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_livemessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LiveMessage",
            new_name="LiveStream",
        ),
    ]
