# Generated by Django 4.1.1 on 2022-11-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_messagenote_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
    ]
