# Generated by Django 4.1.1 on 2023-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_rename_livemessage_livestream"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="video_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
