# Generated by Django 4.1.1 on 2023-07-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_livestream_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="video_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
